### ISSUE TITLE
Doesn't output destination file

### ISSUE THREAD

**Issue by hguiney** [andybluntish/grunt-xsltproc#14]
Config:

    xsltproc: {
      options: {
      stylesheet: '<%= config.app %>/assets/svg2symbol.xslt'
    },
    files: {
      '<%= config.app %>/assets/img/icon.symbol.svg': [
        '<%= config.app %>/assets/img/icon.svg'
      ]
    }

When I run grunt, it silently fails, and the output file is not created.

**Comment by andybluntish** [comment]
G'day Hugh,

It looks like you don't have a target for Grunt to run. Try adding a target to the task configuration, and it should work:

    xsltproc: {
      options: {
      stylesheet: '<%= config.app %>/assets/svg2symbol.xslt'
    },
    icon2symbol: {
      files: {
        '<%= config.app %>/assets/img/icon.symbol.svg': [
          '<%= config.app %>/assets/img/icon.svg'
        ]
      }
    }

Cheers.
