### ISSUE TITLE
Support multiple targets

### ISSUE THREAD

**Issue by dsine-de** [andybluntish/grunt-xsltproc#8]
Hi Andy,

is it possible to add support for target specific stylesheets, so you can have multiple XML and XSL files?

Something like this:

```
xsltproc: {
    options: {
        xinclude: true
    },
    target1: {
        stylesheet: 'stylesheet1.xsl',
        compile: {
            files: {
                'result1.html': ['myxml.xml']
            }
        }
    },
    target2: {
        stylesheet: 'stylesheet2.xsl',
        compile: {
            files: {
                'result2.html': ['../resources/xml/registration.xml']
            }
        }
    }
    ...
```

**Comment by TimSmith714** [comment]
Hi @dsine-de 
Is there any chance you could provide a quick example please. I'm still very new to Grunt and not sure how to do what described as the fix.
Thanks
Tim

**Comment by andybluntish** [comment]
Hi @TimSmith714,

The Grunt docs have a good [section on how to specify options per task target](http://gruntjs.com/configuring-tasks#options) that lays it out pretty well.

You can also look at the [`Gruntfile.js`](https://github.com/andybluntish/grunt-xsltproc/blob/master/Gruntfile.js) in this repository for an example—the `xsltproc` task has multiple targets, each with their own options and files.

Hope this helps.

Cheers.

**Comment by TimSmith714** [comment]
Hi @andybluntish 
Thanks for the links, I've got it sorted out now with separate tasks for the two stylesheets I'm working on. 
Here's my code in case it helps anyone else.
I can't overstate the help this grunt job has been to me. I reckon it's halved the time I needed for a template update and made a job that was terrifying much, much easier.
Kind regards
Tim


    module.exports = function(grunt) {
	  require('time-grunt')(grunt);
    	require('load-grunt-config')(grunt, {
  		jitGrunt:true
	});

	//Loading Tasks
	grunt.loadNpmTasks("grunt-xsltproc");
	grunt.loadNpmTasks("grunt-contrib-watch");

	grunt.initConfig({
		xsltproc: {
			emailA:{
				options: {
					stylesheet: 'src/xslt/emailA.xsl'
				},
					files: [{
						expand: true,
						cwd: 'src/xml',
						src: '*.xml',
						dest: 'dest/a',
						ext: '.html'
					}]
			},
			emailB: {
				options: {
					stylesheet: 'src/xslt/emailB.xsl'
				},
					files: [{
						expand: true,
						cwd: 'src/xml',
						src: '*.xml',
						dest: 'dest/b',
						ext: '.html'
					}]
			}
		},
		watch: {
			targetCW: {
				files: 'src/xslt/emailA.xsl',
				tasks: ['xsltproc:emailA'],
				options: {
					interrupt: true,
					spawn: false,
				}
			},
			targetDA: {
				files:'src/xslt/emailB.xsl',
				tasks: ['xsltproc:emailB'],
				options: {
					interrupt: true,
					spawn: false,
				}
			}
		}
     	})
	//Define the default task
	grunt.registerTask('default',['watch']);
      };
